export const DOCTOR_PERMISSIONS = {
  VIEW: 'OPS_DOCTOR_VIEW',
  CREATE: 'OPS_DOCTOR_CREATE',
  UPDATE: 'OPS_DOCTOR_UPDATE',
  ARCHIVE: 'OPS_DOCTOR_ARCHIVE',
  STATUS_CHANGE: 'OPS_DOCTOR_STATUS_CHANGE'
};