export enum Permission {
  PATIENT_READ = 'PATIENT_READ',
  PATIENT_CREATE = 'PATIENT_CREATE',

  CLINIC_MANAGE = 'CLINIC_MANAGE',

  DOCTOR_READ = 'DOCTOR_READ',
  DOCTOR_MANAGE = 'DOCTOR_MANAGE',

  DEPARTMENT_READ = 'DEPARTMENT_READ',
  DEPARTMENT_MANAGE = 'DEPARTMENT_MANAGE',

  APPOINTMENT_READ = 'APPOINTMENT_READ',
  APPOINTMENT_BOOK = 'APPOINTMENT_BOOK',

  EMR_READ = 'EMR_READ',
  EMR_WRITE = 'EMR_WRITE',

  BILLING_READ = 'BILLING_READ',
  BILLING_WRITE = 'BILLING_WRITE',

  ADMIN_READ = 'ADMIN_READ',
  OPS_EXECUTE = 'OPS_EXECUTE',

  ANALYTICS_READ = 'ANALYTICS_READ'
}
